name: 🎉 Build MassDNS for Windows

on:
  workflow_dispatch:

jobs:
  build_massdns:
    runs-on: windows-latest

    steps:
      - name: Install Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: cmake gcc-g++

      - name: Set Git Line Endings to Unix-style
        run: git config --global core.autocrlf input

      - name: Check Cygwin Installation
        run: |
          ls.exe -Al
          pwd.exe

      - name: Clone Repository
        run: git clone https://github.com/blechschmidt/massdns.git

      - name: Build MassDNS
        run: |
          cd massdns
          mkdir bin
          gcc -O3 -std=c11 -Wall -fstack-protector-strong src/main.c -o bin/massdns.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: massdns
          path: massdns/bin/massdns.exe
