name: "CodeQL"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '26 23 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java
        queries: security-extended,security-and-quality

    - name: Build Log4j Database
      run: |
        git clone https://github.com/apache/logging-log4j2.git
        cd logging-log4j2
        git checkout be881e5
        sed -i '/<module>log4j-layout-template-json/,/<\/modules>/s/^/<!-- /; s/$/ -->/' pom.xml
        mvn clean install -Dmaven.test.skip=true
        cd ..

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:java"

    - name: Upload CodeQL database
      uses: actions/upload-artifact@v3
      with:
        name: codeql-database
        path: ${{ github.workspace }}/results

    - name: Upload CodeQL queries
      run: |
        CODEQL_QUERIES=$(find ${{ github.workspace }}/.github/codeql -name '*.ql')
        if [ -n "$CODEQL_QUERIES" ]; then
          mkdir -p codeql-queries
          cp $CODEQL_QUERIES codeql-queries/
        else
          echo "No .ql files found in .github/codeql directory"
        fi

    - uses: actions/upload-artifact@v3
      with:
        name: codeql-queries
        path: codeql-queries
