name: Build and Upload Massdns for Windows x64

on:
  workflow_dispatch:  # 手动触发工作流程

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cygwin
      run: |
        git config --global core.autocrlf input
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y git
        sudo apt-get install -y make
        sudo apt-get install -y autoconf
        sudo apt-get install -y automake
        sudo apt-get install -y libtool
        sudo apt-get install -y wget
        sudo apt-get install -y unzip
        wget https://cygwin.com/setup-x86_64.exe
        chmod +x setup-x86_64.exe
        ./setup-x86_64.exe --quiet-mode --packages make,git,wget,unzip

    - name: Build Massdns
      run: |
        git clone https://github.com/blechschmidt/massdns.git
        cd massdns
        make nolinux

    - name: Copy binaries
      run: |
        cp massdns/bin/massdns.exe $GITHUB_WORKSPACE/massdns-x64.exe

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: massdns-binaries
        path: $GITHUB_WORKSPACE/massdns-x64.exe
