name: Windows Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Git line endings to Unix-style
        run: git config --global core.autocrlf input

      - name: Set up Cygwin
        uses: cygwin/cygwin-install-action@v4
        with:
          platform: x86_64
          packages: cmake gcc-g++
          install-dir: C:\\cygwin
          site: http://mirrors.kernel.org/sourceware/cygwin/
          add-to-path: true

      - name: Clone repository
        run: git clone https://github.com/blechschmidt/massdns.git

      - name: Set file permissions
        run: icacls massdns /grant Everyone:(F) /T

      - name: Build massdns
        run: |
          C:\\cygwin\\bin\\bash.exe -c "cd massdns && make nolinux"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: massdns
          path: massdns/bin/massdns.exe
