name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 配置 Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: cmake gcc-g++

      - name: Set Git line endings to Unix-style
        run: git config --global core.autocrlf input

      - name: 检查 Cygwin 的安装
        run: |
          ls.exe -Al
          pwd.exe

      - name: 克隆仓库
        run: git clone https://github.com/blechschmidt/massdns.git

      - name: 设置环境变量
        run: echo "::set-env name=CFLAGS::"

      - name: 构建 massdns
        run: |
          cd massdns
          mkdir bin
          gcc $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) -O3 -std=c11 -Wall -fstack-protector-strong src/main.c -o bin/massdns.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: massdns
          path: massdns/bin/massdns.exe
